// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7btPJCQdF4ktqGAPvxnrjb5OH2GOonOk',
    appId: '1:204268989774:web:a805f807c7ec74b63fc21f',
    messagingSenderId: '204268989774',
    projectId: 'task-flow-6fe62',
    authDomain: 'task-flow-6fe62.firebaseapp.com',
    storageBucket: 'task-flow-6fe62.firebasestorage.app',
    measurementId: 'G-74EWHHM0Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGx5VF7P9dBSVgekiA_7qbrK2yHcSCk50',
    appId: '1:204268989774:android:4a4f1e0174064b5f3fc21f',
    messagingSenderId: '204268989774',
    projectId: 'task-flow-6fe62',
    storageBucket: 'task-flow-6fe62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8FFBh8Aga8Upn2-BumJlU7C15jOZjIR0',
    appId: '1:204268989774:ios:647eed72114236d83fc21f',
    messagingSenderId: '204268989774',
    projectId: 'task-flow-6fe62',
    storageBucket: 'task-flow-6fe62.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow',
  );
}
